#!/bin/sh
dir_path="`dirname \"$0\"`"
source $dir_path/../config/token
TEXT=$1
CHANNEL="anime"
curl -s -X POST -d "token=$SLACK_TOKEN&channel=%23$CHANNEL&text=$TEXT&username=anikapi-san&icon_emoji=%3Aanikapi%3A&pretty=1" \
    https://slack.com/api/chat.postMessage > /dev/null

